global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: observability-example
    static_configs:
      - targets:
        - server:8080

rule_files:
  - /etc/prometheus/rules.yml
