{
 "title": "monitoring-example",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "method",
    "query": "label_values(example_requests_count, method)"
   },
   {
    "name": "url",
    "query": "label_values(example_requests_count, url)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request latency",
   "type": "graph",
   "description": "Shows the percentiles of request latency for a specific endpoint",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(example_request_latency_ms_bucket{method=\"$method\",url=\"$url\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(example_request_latency_ms_bucket{method=\"$method\",url=\"$url\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(example_request_latency_ms_bucket{method=\"$method\",url=\"$url\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(example_request_latency_ms_bucket{method=\"$method\",url=\"$url\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Error rate percentage",
   "type": "graph",
   "description": "Shows the error rate percentage of a specific endpoint",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(example_requests_count{method=\"$method\",url=\"$url\",status=~\"5..|4..\"}[7d])) / sum(increase(example_requests_count{method=\"$method\",url=\"$url\"}[7d]))) * 100",
     "legendFormat": "Error rate percentage"
    }
   ]
  },
  {
   "title": "Throughout",
   "type": "graph",
   "description": "Shows the throughput of a specific endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(example_requests_count{method=\"$method\",url=\"$url\"}[5m]))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Trend of error codes",
   "type": "graph",
   "description": "Shows the trend that different error codes are taking",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by(status)(increase(example_requests_count{method=\"$method\",url=\"$url\",status=~\"5..|4..\"}[7d]))"
    }
   ]
  }
 ]
}