{
 "title": "SLI Detail",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "slo_id",
    "label": "SLI Name",
    "query": {
     "query": "label_values(slo:sli:ratio_rate5m, slo_id)"
    }
   },
   { "name": "slo", "label": "SLO", "query": "0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Current SLI",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:sli:ratio_rate5m{slo_id=~\"$slo_id\"}"
    }
   ]
  },
  {
   "title": "Objective (SLO)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$slo" }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1 - $slo" }
   ]
  },
  {
   "title": "Remaining Error Budget",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (1 - slo:sli:ratio_rate5m{slo_id=~\"$slo_id\"}) / (1 - $slo)"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "slo:sli:ratio_rate5m{slo_id=~\"$slo_id\"}",
     "legendFormat": "SLI"
    },
    { "expr": "$slo", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Remaining Error Budget",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (1 - slo:sli:ratio_rate5m{slo_id=~\"$slo_id\"}) / (1 - $slo)",
     "legendFormat": "Error Budget"
    }
   ]
  }
 ]
}